import { Product, Category, Order, Address, User } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    icon: '📱',
    image: 'https://images.unsplash.com/photo-1676173646307-d050e097d181?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWFydHBob25lJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjA2MjIwNzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    productCount: 156,
  },
  {
    id: '2',
    name: 'Fashion',
    icon: '👗',
    image: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwY2xvdGhpbmd8ZW58MXx8fHwxNzYwNzA0MDEzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    productCount: 289,
  },
  {
    id: '3',
    name: 'Beauty',
    icon: '💄',
    image: 'https://images.unsplash.com/photo-1602260395251-0fe691861b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWF1dHklMjBjb3NtZXRpY3N8ZW58MXx8fHwxNzYwNjk1MTI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    productCount: 134,
  },
  {
    id: '4',
    name: 'Home & Living',
    icon: '🏠',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZnVybml0dXJlfGVufDF8fHx8MTc2MDU5NDIwN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    productCount: 198,
  },
  {
    id: '5',
    name: 'Sports',
    icon: '⚽',
    image: 'https://images.unsplash.com/photo-1602211844066-d3bb556e983b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcG9ydHMlMjBlcXVpcG1lbnR8ZW58MXx8fHwxNzYwNjU5OTI5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    productCount: 87,
  },
  {
    id: '6',
    name: 'Books',
    icon: '📚',
    image: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib29rJTIwcmVhZGluZ3xlbnwxfHx8fDE3NjA2MzA3MTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    productCount: 245,
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones Pro',
    price: 299,
    originalPrice: 399,
    rating: 4.5,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1558756520-22cfe5d382ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFkcGhvbmVzJTIwYXVkaW98ZW58MXx8fHwxNzYwNjk5Mjc4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1558756520-22cfe5d382ca?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    ],
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio quality. Perfect for music lovers and professionals.',
    category: 'Electronics',
    stock: 45,
    discount: 25,
    brand: 'AudioTech',
    colors: ['Black', 'Silver', 'Navy Blue'],
    attributes: [
      { label: 'Connectivity', value: 'Bluetooth 5.2' },
      { label: 'Battery Life', value: '30 hours' },
      { label: 'Noise Cancellation', value: 'Active ANC' },
      { label: 'Driver Size', value: '40mm' },
      { label: 'Weight', value: '250g' },
      { label: 'Charging', value: 'USB-C Fast Charging' },
      { label: 'Warranty', value: '2 Years' },
    ],
  },
  {
    id: '2',
    name: 'Designer Sneakers',
    price: 129,
    originalPrice: 179,
    rating: 4.8,
    reviews: 856,
    image: 'https://images.unsplash.com/photo-1656944227480-98180d2a5155?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbmVha2VycyUyMHNob2VzfGVufDF8fHx8MTc2MDY0NTgyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1656944227480-98180d2a5155?w=800',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    ],
    description: 'Comfortable and stylish designer sneakers made with premium materials. Perfect for everyday wear and casual outings.',
    category: 'Fashion',
    stock: 32,
    discount: 28,
    brand: 'StreetStyle',
    sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    colors: ['White', 'Black', 'Navy', 'Gray'],
    attributes: [
      { label: 'Material', value: 'Premium Leather & Mesh' },
      { label: 'Sole Type', value: 'Rubber Non-slip' },
      { label: 'Closure', value: 'Lace-up' },
      { label: 'Toe Shape', value: 'Round Toe' },
      { label: 'Pattern', value: 'Solid' },
      { label: 'Care', value: 'Wipe with clean cloth' },
      { label: 'Warranty', value: '6 Months' },
    ],
  },
  {
    id: '3',
    name: 'Luxury Watch',
    price: 599,
    rating: 4.9,
    reviews: 432,
    image: 'https://images.unsplash.com/photo-1689372828184-fff989d6a553?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXRjaCUyMGFjY2Vzc29yeXxlbnwxfHx8fDE3NjA3MTQ3NjB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1689372828184-fff989d6a553?w=800',
    ],
    description: 'Elegant luxury watch with automatic movement, sapphire crystal, and water resistance up to 100m. A timeless accessory for any occasion.',
    category: 'Fashion',
    stock: 18,
    brand: 'TimeGrand',
    colors: ['Silver', 'Gold', 'Rose Gold'],
    attributes: [
      { label: 'Movement', value: 'Automatic Mechanical' },
      { label: 'Case Material', value: 'Stainless Steel' },
      { label: 'Case Diameter', value: '42mm' },
      { label: 'Water Resistance', value: '100m / 10 ATM' },
      { label: 'Crystal', value: 'Sapphire Crystal' },
      { label: 'Band Material', value: 'Stainless Steel Bracelet' },
      { label: 'Warranty', value: '3 Years International' },
    ],
  },
  {
    id: '4',
    name: 'Modern Laptop',
    price: 1299,
    originalPrice: 1499,
    rating: 4.7,
    reviews: 2103,
    image: 'https://images.unsplash.com/photo-1511385348-a52b4a160dc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlcnxlbnwxfHx8fDE3NjA2Nzc0NTl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1511385348-a52b4a160dc2?w=800',
    ],
    description: 'High-performance laptop with latest generation processor, 16GB RAM, 512GB SSD, and stunning display. Perfect for work and entertainment.',
    category: 'Electronics',
    stock: 25,
    discount: 13,
    brand: 'TechPro',
    colors: ['Space Gray', 'Silver'],
    attributes: [
      { label: 'Processor', value: 'Intel Core i7 12th Gen' },
      { label: 'RAM', value: '16GB DDR4' },
      { label: 'Storage', value: '512GB NVMe SSD' },
      { label: 'Display', value: '15.6" FHD IPS (1920x1080)' },
      { label: 'Graphics', value: 'Intel Iris Xe' },
      { label: 'Operating System', value: 'Windows 11 Pro' },
      { label: 'Battery', value: 'Up to 10 hours' },
      { label: 'Weight', value: '1.8kg' },
      { label: 'Warranty', value: '1 Year' },
    ],
  },
  {
    id: '5',
    name: 'Designer Handbag',
    price: 449,
    rating: 4.6,
    reviews: 678,
    image: 'https://images.unsplash.com/photo-1751522937993-46b83342398b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kYmFnJTIwcHVyc2V8ZW58MXx8fHwxNzYwNzEwNzQ5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1751522937993-46b83342398b?w=800',
    ],
    description: 'Elegant designer handbag crafted from premium leather. Spacious interior with multiple compartments for all your essentials.',
    category: 'Fashion',
    stock: 28,
    brand: 'LuxeMode',
    colors: ['Black', 'Brown', 'Beige', 'Navy'],
    attributes: [
      { label: 'Material', value: 'Genuine Leather' },
      { label: 'Dimensions', value: '32cm x 25cm x 12cm' },
      { label: 'Closure Type', value: 'Magnetic Snap' },
      { label: 'Interior', value: '3 compartments + 2 pockets' },
      { label: 'Strap', value: 'Adjustable shoulder strap' },
      { label: 'Lining', value: 'Polyester' },
      { label: 'Care', value: 'Leather conditioner recommended' },
      { label: 'Warranty', value: '1 Year' },
    ],
  },
  {
    id: '6',
    name: 'Stylish Sunglasses',
    price: 159,
    originalPrice: 229,
    rating: 4.4,
    reviews: 543,
    image: 'https://images.unsplash.com/photo-1718967807816-414e2f9bc95a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdW5nbGFzc2VzJTIwZmFzaGlvbnxlbnwxfHx8fDE3NjA2MzA5MTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1718967807816-414e2f9bc95a?w=800',
    ],
    description: 'Premium polarized sunglasses with UV protection. Lightweight frame and scratch-resistant lenses for all-day comfort.',
    category: 'Fashion',
    stock: 56,
    discount: 31,
    brand: 'SunStyle',
    colors: ['Black', 'Tortoise', 'Matte Black', 'Brown'],
    attributes: [
      { label: 'Lens Type', value: 'Polarized' },
      { label: 'UV Protection', value: 'UV400' },
      { label: 'Frame Material', value: 'Acetate' },
      { label: 'Lens Material', value: 'TAC Polarized' },
      { label: 'Lens Width', value: '55mm' },
      { label: 'Bridge Width', value: '18mm' },
      { label: 'Features', value: 'Scratch-resistant coating' },
      { label: 'Warranty', value: '1 Year' },
    ],
  },
  {
    id: '7',
    name: 'Smart Fitness Watch',
    price: 249,
    originalPrice: 329,
    rating: 4.5,
    reviews: 1890,
    image: 'https://images.unsplash.com/photo-1689372828184-fff989d6a553?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXRjaCUyMGFjY2Vzc29yeXxlbnwxfHx8fDE3NjA3MTQ3NjB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1689372828184-fff989d6a553?w=800',
    ],
    description: 'Track your fitness goals with this advanced smartwatch featuring heart rate monitoring, GPS, and 7-day battery life.',
    category: 'Electronics',
    stock: 67,
    discount: 24,
    brand: 'FitTech',
    sizes: ['40mm', '44mm'],
    colors: ['Black', 'White', 'Blue', 'Pink'],
    attributes: [
      { label: 'Display', value: '1.4" AMOLED Touchscreen' },
      { label: 'Sensors', value: 'Heart Rate, SpO2, GPS' },
      { label: 'Battery Life', value: 'Up to 7 days' },
      { label: 'Water Resistance', value: '5 ATM (50m)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0' },
      { label: 'Sports Modes', value: '100+ Exercise modes' },
      { label: 'Compatibility', value: 'iOS & Android' },
      { label: 'Warranty', value: '1 Year' },
    ],
  },
  {
    id: '8',
    name: 'Premium Smartphone',
    price: 899,
    originalPrice: 1099,
    rating: 4.8,
    reviews: 3421,
    image: 'https://images.unsplash.com/photo-1676173646307-d050e097d181?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWFydHBob25lJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjA2MjIwNzJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1676173646307-d050e097d181?w=800',
    ],
    description: 'Latest generation smartphone with advanced camera system, 5G connectivity, and all-day battery life.',
    category: 'Electronics',
    stock: 42,
    discount: 18,
    brand: 'PhonePro',
    colors: ['Midnight Black', 'Starlight Silver', 'Aurora Blue', 'Sunset Gold'],
    attributes: [
      { label: 'Display', value: '6.7" AMOLED 120Hz' },
      { label: 'Processor', value: 'Snapdragon 8 Gen 2' },
      { label: 'RAM', value: '12GB' },
      { label: 'Storage', value: '256GB' },
      { label: 'Camera', value: '50MP + 12MP + 8MP' },
      { label: 'Front Camera', value: '32MP' },
      { label: 'Battery', value: '5000mAh with 65W fast charging' },
      { label: 'Network', value: '5G, 4G LTE' },
      { label: 'OS', value: 'Android 13' },
      { label: 'Warranty', value: '1 Year' },
    ],
  },
];

export const mockUser: User = {
  id: '1',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@example.com',
  phone: '+1 234 567 8900',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
};

export const mockAddresses: Address[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    phone: '+1 234 567 8900',
    addressLine1: '123 Main Street',
    addressLine2: 'Apt 4B',
    city: 'New York',
    state: 'NY',
    pincode: '10001',
    isDefault: true,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    phone: '+1 234 567 8900',
    addressLine1: '456 Park Avenue',
    city: 'Brooklyn',
    state: 'NY',
    pincode: '11201',
    isDefault: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    date: '2025-10-15',
    status: 'delivered',
    items: [
      { product: products[0], quantity: 1 },
      { product: products[1], quantity: 2 },
    ],
    total: 557,
    address: mockAddresses[0],
  },
  {
    id: 'ORD-2025-002',
    date: '2025-10-16',
    status: 'pending',
    items: [
      { product: products[3], quantity: 1 },
    ],
    total: 1299,
    address: mockAddresses[0],
  },
  {
    id: 'ORD-2025-003',
    date: '2025-10-10',
    status: 'shipped',
    items: [
      { product: products[2], quantity: 1 },
      { product: products[5], quantity: 1 },
    ],
    total: 758,
    address: mockAddresses[1],
  },
];
